### PR TITLE
Mjh91/num beats

### PR DESCRIPTION
**Pull request by mackenna95**

### CODE REVIEW

**Comment by mackenna95** [comment]
@mlp6 @suyashkumar -- RESOLVED

I did not realize that I named an attribute and function the same thing within the class HeartRateMonitor. The issue is now resolved.

------

Not sure what is throwing this TypeError. pytest states that it is the line 
'peak_times = self.beats(data)'
I believe this means that data has type 'NoneType' which does not make sense to me since I was able to execute the previous line
'self.return_duration(data)'

Also, note that the code was working well until I introduced a new self. call 'self.beats(data)' 
Since 3 of the attributes need 'peak_times' I decided to write the autocorrelation function and peak detection in self.beats and output 'peak_times' for use in subsequent self. calls

Further note. The rest of the code and tests work fine if the line
'peak_times = self.beats(data)'
is altered to
'peak_times = [1, 2, 3]'
representing 3 peaks at 1, 2, and 3 seconds.

**Comment by mlp6** [comment]
Usually these errors are PEBKACs.  Been there.  Done that.

**Comment by mackenna95** [comment]
@mlp6 Any suggestion for this specific one? I can run code fine in ipython (2.7) but it raises an error in pytest (python 3.6). I know I could just add the last indicie on again anytime numpy autocorrelation returns an odd number but that seems like a poor fix for the issue.

In [1]: from heart_rate_monitor import HeartRateMonitor
In [2]: output = HeartRateMonitor("test_data1.csv", [1, 1], [1, 1])
In [3]: output.num_beats
Out[3]: 35

pytest
>       output = HeartRateMonitor("test_data1.csv", [1, 1], [1, 1]) # can't run this without error
...
>           temp = autocorr[autocorr.size/2:]/autocorr[autocorr.size/2] # erros on this line
E           TypeError: slice indices must be integers or None or have an __index__ method


Full pytest output below.





================================== FAILURES ===================================
___________________________ test_heart_rate_monitor ___________________________

    def test_heart_rate_monitor():
        import pytest
        from heart_rate_monitor import HeartRateMonitor

        tolerance = 0.0000001

>       output = HeartRateMonitor("test_data1.csv", [1, 1], [1, 1])

test_heart_rate_monitor.py:7:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
heart_rate_monitor.py:52: in __init__
    peak_times = self.beat_calculation(data)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <heart_rate_monitor.HeartRateMonitor object at 0x0000013FF13F3EF0>
data = array([[0.000000e+00, 1.865980e-01],
       [3.000000e-03, 1.865980e-01],
       [6.000000e-03, 1.865980e-01],
       ...,
       [2.776900e+01, 1.041598e+00],
       [2.777200e+01, 1.126598e+00],
       [2.777500e+01, 1.051598e+00]])

    def beat_calculation(self, data):
        """
            :param self:         ECG data
            :returns peak_times: all beat times in dataset
            :raises TypeError:   value not int or float
            :raises ValueError:  list is empty
            :raises ImportError: packages not found
            """

        import logging
        logging.basicConfig(filename="heart_rate_monitor_log.txt",
                            format='%(asctime)s %(message)s',
                            datefmt='%m/%d/%Y %I:%M:%S %p')

        if not self:
            logging.warning('Your list is empty')
            raise ValueError("list is empty")

        try:
            mean = np.mean(data[:, 1])
            data[:,1] -= np.mean(data[:, 1])
            autocorr = np.correlate(data[:, 1], data[:, 1], mode='full')
>           temp = autocorr[autocorr.size/2:]/autocorr[autocorr.size/2]
E           TypeError: slice indices must be integers or None or have an __index__ method

heart_rate_monitor.py:178: TypeError
------------------------------ Captured log call ------------------------------
heart_rate_monitor.py       85 INFO     Success: data as np array returned.
heart_rate_monitor.py      120 INFO     Success: voltage_extreemes returned.
heart_rate_monitor.py      154 INFO     Success: duration returned.
========================== 1 failed in 0.48 seconds ===========================

**Comment by mlp6** [comment]
Is `autocorr.size` an odd number?  Dividing that by 2 would yield a non-integer value, which would not be valid (but that should also fail in `python2.7`).

**Comment by mackenna95** [comment]
@mlp6 @suyashkumar -- RESOLVED

Was able to fix it by forcing the index to be an int. Still not sure why it didn't cause an error when running in ipython.

---------------------------------------------------------

autocorr.size (the output of the following line) is odd.
autocorr = np.correlate(data[:, 1], data[:, 1], mode='full')
when data.size = 10,000 autocorr.size = 19,999
I am getting no error when I run the code in ipython (and I checked to make sure autocorr.size = odd). It should be an error in ipython but somehow the code can make it work with no error.

Just tried a simple version in ipython (2.7):
In [14]: a = np.array([1,2,3,4,5])
In [15]: b = a[a.size/2:]/a[a.size/2]
In [16]: b
Out[16]: array([1, 1, 1])

Update:
Placed the same code in my function and ran pytest. Again, pytest errored while ipython did not. Also, pytest is the only thing erroring. I can run the code inside HeartRateMonitor class and outside of it in ipython with no issue. 

Update:
ensured the autocorr.size was even by adding the last index on again if autocorr.size was odd. This STILL caused the same error. Again, no error in ipython. 
Attempted to force an int using the following code
temp = autocorr[int(autocorr.size/2):]/autocorr[int(autocorr.size/2)]
error arose 
E           IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
No idea how to fix this since it is only an issue with pytest.
Should I commit this even though pytest is now un-useable?

**Comment by mackenna95** [comment]
@mlp6 response above

**Pull request merged**
